server:
  port: 8761
eureka:
  #  关闭自我保护模式
  #  eureka.server.enable-self-preservation: false
  instance:
    #服务名，默认取 spring.application.name 配置值，如果没有则为 unknown
    appname: provider-service
    #设置当前实例的主机名称
    hostname: localhost
  client:
    #是否将自己注册到Eureka-Server中，默认的为true
    register-with-eureka: false
    #是否冲Eureka-Server中获取服务注册信息，默认为true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/